'Generated by the GOLD Parser Builder

Option Explicit On
Option Strict Off

Imports System.IO
Imports System.Windows.Forms;


Module MyParser
    Private Parser As New GOLD.Parser

    Private Enum SymbolIndex
        [Eof] = 0                                 ' (EOF)
        [Error] = 1                               ' (Error)
        [Comment] = 2                             ' Comment
        [Newline] = 3                             ' NewLine
        [Whitespace] = 4                          ' Whitespace
        [Num] = 5                                 ' '#'
        [Numtimes] = 6                            ' '#*'
        [Timesnum] = 7                            ' '*#'
        [Minus] = 8                               ' '-'
        [Minusminus] = 9                          ' '--'
        [Exclam] = 10                             ' '!'
        [Exclameq] = 11                           ' '!='
        [Ampamp] = 12                             ' '&&'
        [Lparen] = 13                             ' '('
        [Rparen] = 14                             ' ')'
        [Times] = 15                              ' '*'
        [Comma] = 16                              ' ','
        [Dot] = 17                                ' '.'
        [Div] = 18                                ' '/'
        [Colon] = 19                              ' ':'
        [Semi] = 20                               ' ';'
        [Caret] = 21                              ' '^'
        [Lbrace] = 22                             ' '{'
        [Pipepipe] = 23                           ' '||'
        [Rbrace] = 24                             ' '}'
        [Plus] = 25                               ' '+'
        [Plusplus] = 26                           ' '++'
        [Lt] = 27                                 ' '<'
        [Ltlt] = 28                               ' '<<'
        [Lteq] = 29                               ' '<='
        [Eq] = 30                                 ' '='
        [Eqeq] = 31                               ' '=='
        [Gt] = 32                                 ' '>'
        [Gteq] = 33                               ' '>='
        [Gtgt] = 34                               ' '>>'
        [Actualizar] = 35                         ' ACTUALIZAR
        [Agregar] = 36                            ' AGREGAR
        [Alterar] = 37                            ' ALTERAR
        [Asc] = 38                                ' ASC
        [Autoincrementable] = 39                  ' Autoincrementable
        [Backup] = 40                             ' BACKUP
        [Base_datos] = 41                         ' 'BASE_DATOS'
        [Bool] = 42                               ' BOOL
        [Borrar] = 43                             ' BORRAR
        [Cadena] = 44                             ' Cadena
        [Cambiar] = 45                            ' CAMBIAR
        [Caso] = 46                               ' CASO
        [Colocar] = 47                            ' COLOCAR
        [Completo] = 48                           ' COMPLETO
        [Contar] = 49                             ' CONTAR
        [Crear] = 50                              ' CREAR
        [Date] = 51                               ' DATE
        [Datetime] = 52                           ' DATETIME
        [De] = 53                                 ' DE
        [Declarar] = 54                           ' DECLARAR
        [Defecto] = 55                            ' DEFECTO
        [Denegar] = 56                            ' DENEGAR
        [Desc] = 57                               ' DESC
        [Detener] = 58                            ' DETENER
        [Doble] = 59                              ' Doble
        [Donde] = 60                              ' DONDE
        [Double] = 61                             ' DOUBLE
        [Eliminar] = 62                           ' ELIMINAR
        [En] = 63                                 ' EN
        [Entero] = 64                             ' Entero
        [Fecha] = 65                              ' Fecha
        [Fecha_hora] = 66                         ' 'FECHA_HORA'
        [Fechahora] = 67                          ' FechaHora
        [Funcion] = 68                            ' FUNCION
        [Identificador] = 69                      ' identificador
        [Imprimir] = 70                           ' IMPRIMIR
        [Insertar] = 71                           ' INSERTAR
        [Integer] = 72                            ' INTEGER
        [Llave_foranea] = 73                      ' 'Llave_Foranea'
        [Llave_primaria] = 74                     ' 'Llave_Primaria'
        [Mientras] = 75                           ' MIENTRAS
        [No] = 76                                 ' NO
        [Nulo] = 77                               ' Nulo
        [Objeto] = 78                             ' OBJETO
        [Ordenar_por] = 79                        ' 'ORDENAR_POR'
        [Otorgar] = 80                            ' OTORGAR
        [Para] = 81                               ' PARA
        [Password] = 82                           ' password
        [Permisos] = 83                           ' PERMISOS
        [Procedimiento] = 84                      ' PROCEDIMIENTO
        [Quitar] = 85                             ' QUITAR
        [Restaurar] = 86                          ' RESTAURAR
        [Retorno] = 87                            ' RETORNO
        [Selecciona] = 88                         ' SELECCIONA
        [Seleccionar] = 89                        ' SELECCIONAR
        [Si] = 90                                 ' SI
        [Sino] = 91                               ' SINO
        [Tabla] = 92                              ' TABLA
        [Text] = 93                               ' TEXT
        [Unico] = 94                              ' UNICO
        [Usar] = 95                               ' USAR
        [Usqldump] = 96                           ' USQLDUMP
        [Usuario] = 97                            ' USUARIO
        [Valores] = 98                            ' VALORES
        [Variable] = 99                           ' Variable
        [Actualizar2] = 100                       ' <actualizar>
        [Alterar2] = 101                          ' <alterar>
        [Alterarobjeto] = 102                     ' <alterarobjeto>
        [Alterartabla] = 103                      ' <alterartabla>
        [Aritemtica] = 104                        ' <aritemtica>
        [Asignacion] = 105                        ' <asignacion>
        [Back] = 106                              ' <back>
        [Borrar2] = 107                           ' <borrar>
        [C_base] = 108                            ' <c_base>
        [C_funcion] = 109                         ' <c_funcion>
        [C_objeto] = 110                          ' <c_objeto>
        [C_pro] = 111                             ' <c_pro>
        [C_tabla] = 112                           ' <c_tabla>
        [C_usuario] = 113                         ' <c_usuario>
        [Campo_tabla] = 114                       ' <campo_tabla>
        [Campos] = 115                            ' <campos>
        [Campos_tabla] = 116                      ' <campos_tabla>
        [Caso2] = 117                             ' <caso>
        [Casos] = 118                             ' <casos>
        [Complemento] = 119                       ' <complemento>
        [Complementos] = 120                      ' <complementos>
        [Condicion] = 121                         ' <condicion>
        [Contar2] = 122                           ' <contar>
        [Contarasig] = 123                        ' <contarAsig>
        [Crear2] = 124                            ' <crear>
        [Declarar2] = 125                         ' <declarar>
        [Defecto2] = 126                          ' <defecto>
        [Denegar2] = 127                          ' <denegar>
        [Eliminar2] = 128                         ' <eliminar>
        [Expresion] = 129                         ' <expresion>
        [Id] = 130                                ' <ID>
        [Imprimir2] = 131                         ' <imprimir>
        [Inicio] = 132                            ' <Inicio>
        [Insertar2] = 133                         ' <insertar>
        [Instruccion] = 134                       ' <instruccion>
        [Instrucciones] = 135                     ' <instrucciones>
        [Instruccionesr] = 136                    ' <instruccionesR>
        [Llamada] = 137                           ' <llamada>
        [Logica] = 138                            ' <logica>
        [Logica_consulta] = 139                   ' <logica_consulta>
        [Logica_consultas] = 140                  ' <logica_consultas>
        [Opciones_c] = 141                        ' <opciones_c>
        [Opciones_for] = 142                      ' <opciones_for>
        [Orden] = 143                             ' <orden>
        [Otorgar2] = 144                          ' <otorgar>
        [Parametro] = 145                         ' <parametro>
        [Parametros] = 146                        ' <parametros>
        [Relacional] = 147                        ' <relacional>
        [Restaurar2] = 148                        ' <restaurar>
        [Retorno2] = 149                          ' <retorno>
        [Rno] = 150                               ' <RNO>
        [Rnulo] = 151                             ' <RNULO>
        [Rutab] = 152                             ' <rutaB>
        [S] = 153                                 ' <S>
        [Seleccionar2] = 154                      ' <seleccionar>
        [Seleccionarf] = 155                      ' <seleccionarf>
        [Sentencia] = 156                         ' <sentencia>
        [Sentencias] = 157                        ' <sentencias>
        [Sino2] = 158                             ' <sino>
        [Tfor] = 159                              ' <Tfor>
        [Tif] = 160                               ' <Tif>
        [Tipo_dato] = 161                         ' <tipo_dato>
        [Tipoins] = 162                           ' <tipoins>
        [Tswitch] = 163                           ' <Tswitch>
        [Twhile] = 164                            ' <Twhile>
        [Usar2] = 165                             ' <usar>
        [Valores2] = 166                          ' <valores>
        [Variables] = 167                         ' <variables>
    End Enum

    Private Enum ProductionIndex
        [S] = 0                                   ' <S> ::= <Inicio>
        [Inicio] = 1                              ' <Inicio> ::= <sentencias>
        [Sentencias] = 2                          ' <sentencias> ::= <sentencia> <sentencias>
        [Sentencias2] = 3                         ' <sentencias> ::= <sentencia>
        [Sentencia] = 4                           ' <sentencia> ::= <usar>
        [Sentencia2] = 5                          ' <sentencia> ::= <crear>
        [Sentencia3] = 6                          ' <sentencia> ::= <imprimir>
        [Sentencia4] = 7                          ' <sentencia> ::= <insertar>
        [Sentencia5] = 8                          ' <sentencia> ::= <actualizar>
        [Sentencia6] = 9                          ' <sentencia> ::= <borrar>
        [Sentencia7] = 10                         ' <sentencia> ::= <seleccionar>
        [Sentencia8] = 11                         ' <sentencia> ::= <otorgar>
        [Sentencia9] = 12                         ' <sentencia> ::= <denegar>
        [Sentencia10] = 13                        ' <sentencia> ::= <back>
        [Sentencia11] = 14                        ' <sentencia> ::= <restaurar>
        [Sentencia12] = 15                        ' <sentencia> ::= <alterar>
        [Sentencia13] = 16                        ' <sentencia> ::= <eliminar>
        [Sentencia14] = 17                        ' <sentencia> ::= <declarar>
        [Sentencia_Semi] = 18                     ' <sentencia> ::= <llamada> ';'
        [Usar_Usar_Semi] = 19                     ' <usar> ::= USAR <ID> ';'
        [Crear_Crear] = 20                        ' <crear> ::= CREAR <opciones_c>
        [Opciones_c] = 21                         ' <opciones_c> ::= <c_base>
        [Opciones_c2] = 22                        ' <opciones_c> ::= <c_tabla>
        [Opciones_c3] = 23                        ' <opciones_c> ::= <c_objeto>
        [Opciones_c4] = 24                        ' <opciones_c> ::= <c_pro>
        [Opciones_c5] = 25                        ' <opciones_c> ::= <c_funcion>
        [Opciones_c6] = 26                        ' <opciones_c> ::= <c_usuario>
        [C_base_Base_datos_Semi] = 27             ' <c_base> ::= 'BASE_DATOS' <ID> ';'
        [C_tabla_Tabla_Lparen_Rparen_Semi] = 28   ' <c_tabla> ::= TABLA <ID> '(' <campos_tabla> ')' ';'
        [Campos_tabla_Comma] = 29                 ' <campos_tabla> ::= <campo_tabla> ',' <campos_tabla>
        [Campos_tabla] = 30                       ' <campos_tabla> ::= <campo_tabla>
        [Campo_tabla] = 31                        ' <campo_tabla> ::= <tipo_dato> <ID> <complementos>
        [Campo_tabla2] = 32                       ' <campo_tabla> ::= <tipo_dato> <ID>
        [Campo_tabla3] = 33                       ' <campo_tabla> ::= <ID> <ID> <complementos>
        [Campo_tabla4] = 34                       ' <campo_tabla> ::= <ID> <ID>
        [Complementos] = 35                       ' <complementos> ::= <complemento> <complementos>
        [Complementos2] = 36                      ' <complementos> ::= <complemento>
        [Complemento] = 37                        ' <complemento> ::= <RNO>
        [Complemento2] = 38                       ' <complemento> ::= <RNULO>
        [Complemento_Autoincrementable] = 39      ' <complemento> ::= Autoincrementable
        [Complemento_Llave_primaria] = 40         ' <complemento> ::= 'Llave_Primaria'
        [Complemento_Llave_foranea] = 41          ' <complemento> ::= 'Llave_Foranea' <ID>
        [Complemento_Unico] = 42                  ' <complemento> ::= UNICO
        [C_objeto_Objeto_Lparen_Rparen_Semi] = 43 ' <c_objeto> ::= OBJETO <ID> '(' <parametros> ')' ';'
        [C_objeto_Objeto_Lparen_Rparen_Semi2] = 44 ' <c_objeto> ::= OBJETO <ID> '(' ')' ';'
        [Parametros_Comma] = 45                   ' <parametros> ::= <parametros> ',' <parametro>
        [Parametros] = 46                         ' <parametros> ::= <parametro>
        [Parametro] = 47                          ' <parametro> ::= <tipo_dato> <ID>
        [Parametro_Variable] = 48                 ' <parametro> ::= <tipo_dato> Variable
        [C_pro_Procedimiento_Lparen_Rparen_Lbrace_Rbrace] = 49 ' <c_pro> ::= PROCEDIMIENTO <ID> '(' <parametros> ')' '{' <instrucciones> '}'
        [C_pro_Procedimiento_Lparen_Rparen_Lbrace_Rbrace2] = 50 ' <c_pro> ::= PROCEDIMIENTO <ID> '(' ')' '{' <instrucciones> '}'
        [Instrucciones] = 51                      ' <instrucciones> ::= <instruccion> <instrucciones>
        [Instrucciones2] = 52                     ' <instrucciones> ::= <instruccion>
        [Instruccion] = 53                        ' <instruccion> ::= <asignacion>
        [Instruccion2] = 54                       ' <instruccion> ::= <Tif>
        [Instruccion3] = 55                       ' <instruccion> ::= <Tswitch>
        [Instruccion4] = 56                       ' <instruccion> ::= <Tfor>
        [Instruccion5] = 57                       ' <instruccion> ::= <Twhile>
        [Instruccion6] = 58                       ' <instruccion> ::= <sentencia>
        [Instruccion_Detener_Semi] = 59           ' <instruccion> ::= DETENER ';'
        [C_funcion_Funcion_Lparen_Rparen_Lbrace_Rbrace] = 60 ' <c_funcion> ::= FUNCION <ID> '(' <parametros> ')' <tipo_dato> '{' <instruccionesR> '}'
        [C_funcion_Funcion_Lparen_Rparen_Lbrace_Rbrace2] = 61 ' <c_funcion> ::= FUNCION <ID> '(' <parametros> ')' <ID> '{' <instruccionesR> '}'
        [C_funcion_Funcion_Lparen_Rparen_Lbrace_Rbrace3] = 62 ' <c_funcion> ::= FUNCION <ID> '(' ')' <tipo_dato> '{' <instruccionesR> '}'
        [C_funcion_Funcion_Lparen_Rparen_Lbrace_Rbrace4] = 63 ' <c_funcion> ::= FUNCION <ID> '(' ')' <ID> '{' <instruccionesR> '}'
        [Instruccionesr] = 64                     ' <instruccionesR> ::= <instrucciones> <retorno>
        [Retorno_Retorno_Semi] = 65               ' <retorno> ::= RETORNO <aritemtica> ';'
        [C_usuario_Usuario_Colocar_Password_Eq_Cadena_Semi] = 66 ' <c_usuario> ::= USUARIO <ID> COLOCAR password '=' Cadena ';'
        [Imprimir_Imprimir_Lparen_Rparen_Semi] = 67 ' <imprimir> ::= IMPRIMIR '(' <expresion> ')' ';'
        [Insertar_Insertar_En_Tabla] = 68         ' <insertar> ::= INSERTAR EN TABLA <ID> <tipoins>
        [Tipoins_Lparen_Rparen_Valores_Lparen_Rparen_Semi] = 69 ' <tipoins> ::= '(' <campos> ')' VALORES '(' <valores> ')' ';'
        [Tipoins_Lparen_Rparen_Semi] = 70         ' <tipoins> ::= '(' <valores> ')' ';'
        [Campos_Comma] = 71                       ' <campos> ::= <campos> ',' <rutaB>
        [Campos] = 72                             ' <campos> ::= <rutaB>
        [Valores_Comma] = 73                      ' <valores> ::= <aritemtica> ',' <valores>
        [Valores] = 74                            ' <valores> ::= <aritemtica>
        [Actualizar_Actualizar_Tabla_Lparen_Rparen_Valores_Lparen_Rparen_Semi] = 75 ' <actualizar> ::= ACTUALIZAR TABLA <ID> '(' <campos> ')' VALORES '(' <valores> ')' <condicion> ';'
        [Actualizar_Actualizar_Tabla_Lparen_Rparen_Valores_Lparen_Rparen_Semi2] = 76 ' <actualizar> ::= ACTUALIZAR TABLA <ID> '(' <campos> ')' VALORES '(' <valores> ')' ';'
        [Condicion_Donde] = 77                    ' <condicion> ::= DONDE <logica_consultas>
        [Borrar_Borrar_En_Tabla_Semi] = 78        ' <borrar> ::= BORRAR EN TABLA <ID> <condicion> ';'
        [Borrar_Borrar_En_Tabla_Semi2] = 79       ' <borrar> ::= BORRAR EN TABLA <ID> ';'
        [Seleccionar_Seleccionar_De_Semi] = 80    ' <seleccionar> ::= SELECCIONAR <campos> DE <campos> <condicion> <orden> ';'
        [Seleccionar_Seleccionar_Times_De_Semi] = 81 ' <seleccionar> ::= SELECCIONAR '*' DE <campos> <condicion> <orden> ';'
        [Seleccionar_Seleccionar_De_Semi2] = 82   ' <seleccionar> ::= SELECCIONAR <campos> DE <campos> <condicion> ';'
        [Seleccionar_Seleccionar_Times_De_Semi2] = 83 ' <seleccionar> ::= SELECCIONAR '*' DE <campos> <condicion> ';'
        [Seleccionar_Seleccionar_De_Semi3] = 84   ' <seleccionar> ::= SELECCIONAR <campos> DE <campos> <orden> ';'
        [Seleccionar_Seleccionar_Times_De_Semi3] = 85 ' <seleccionar> ::= SELECCIONAR '*' DE <campos> <orden> ';'
        [Seleccionar_Seleccionar_De_Semi4] = 86   ' <seleccionar> ::= SELECCIONAR <campos> DE <campos> ';'
        [Seleccionar_Seleccionar_Times_De_Semi4] = 87 ' <seleccionar> ::= SELECCIONAR '*' DE <campos> ';'
        [Seleccionarf_Seleccionar_De] = 88        ' <seleccionarf> ::= SELECCIONAR <campos> DE <campos> <condicion> <orden>
        [Seleccionarf_Seleccionar_Times_De] = 89  ' <seleccionarf> ::= SELECCIONAR '*' DE <campos> <condicion> <orden>
        [Seleccionarf_Seleccionar_De2] = 90       ' <seleccionarf> ::= SELECCIONAR <campos> DE <campos> <condicion>
        [Seleccionarf_Seleccionar_Times_De2] = 91 ' <seleccionarf> ::= SELECCIONAR '*' DE <campos> <condicion>
        [Seleccionarf_Seleccionar_De3] = 92       ' <seleccionarf> ::= SELECCIONAR <campos> DE <campos> <orden>
        [Seleccionarf_Seleccionar_Times_De3] = 93 ' <seleccionarf> ::= SELECCIONAR '*' DE <campos> <orden>
        [Seleccionarf_Seleccionar_De4] = 94       ' <seleccionarf> ::= SELECCIONAR <campos> DE <campos>
        [Seleccionarf_Seleccionar_Times_De4] = 95 ' <seleccionarf> ::= SELECCIONAR '*' DE <campos>
        [Orden_Ordenar_por_Asc] = 96              ' <orden> ::= 'ORDENAR_POR' <ID> ASC
        [Orden_Ordenar_por_Desc] = 97             ' <orden> ::= 'ORDENAR_POR' <ID> DESC
        [Orden_Ordenar_por] = 98                  ' <orden> ::= 'ORDENAR_POR' <ID>
        [Otorgar_Otorgar_Permisos_Comma_Semi] = 99 ' <otorgar> ::= OTORGAR PERMISOS <ID> ',' <rutaB> ';'
        [Rutab_Dot] = 100                         ' <rutaB> ::= <ID> '.' <rutaB>
        [Rutab_Variable_Dot] = 101                ' <rutaB> ::= Variable '.' <rutaB>
        [Rutab_Variable] = 102                    ' <rutaB> ::= Variable
        [Rutab] = 103                             ' <rutaB> ::= <ID>
        [Rutab_Times] = 104                       ' <rutaB> ::= '*'
        [Denegar_Denegar_Permisos_Comma_Semi] = 105 ' <denegar> ::= DENEGAR PERMISOS <ID> ',' <rutaB> ';'
        [Back_Backup_Usqldump_Semi] = 106         ' <back> ::= BACKUP USQLDUMP <ID> <ID> ';'
        [Back_Backup_Completo_Semi] = 107         ' <back> ::= BACKUP COMPLETO <ID> <ID> ';'
        [Restaurar_Restaurar_Usqldump_Cadena_Semi] = 108 ' <restaurar> ::= RESTAURAR USQLDUMP Cadena ';'
        [Restaurar_Restaurar_Completo_Cadena_Semi] = 109 ' <restaurar> ::= RESTAURAR COMPLETO Cadena ';'
        [Alterar_Alterar_Tabla_Semi] = 110        ' <alterar> ::= ALTERAR TABLA <ID> <alterartabla> ';'
        [Alterar_Alterar_Objeto_Semi] = 111       ' <alterar> ::= ALTERAR OBJETO <ID> <alterarobjeto> ';'
        [Alterar_Alterar_Usuario_Cambiar_Password_Eq_Cadena] = 112 ' <alterar> ::= ALTERAR USUARIO <ID> CAMBIAR password '=' Cadena
        [Alterartabla_Agregar_Lparen_Rparen] = 113 ' <alterartabla> ::= AGREGAR '(' <campos_tabla> ')'
        [Alterartabla_Quitar] = 114               ' <alterartabla> ::= QUITAR <campos>
        [Alterarobjeto_Agregar_Lparen_Rparen] = 115 ' <alterarobjeto> ::= AGREGAR '(' <parametros> ')'
        [Alterarobjeto_Quitar] = 116              ' <alterarobjeto> ::= QUITAR <campos>
        [Eliminar_Eliminar_Tabla_Semi] = 117      ' <eliminar> ::= ELIMINAR TABLA <ID> ';'
        [Eliminar_Eliminar_Base_datos_Semi] = 118 ' <eliminar> ::= ELIMINAR 'BASE_DATOS' <ID> ';'
        [Eliminar_Eliminar_Objeto_Semi] = 119     ' <eliminar> ::= ELIMINAR OBJETO <ID> ';'
        [Eliminar_Eliminar_Usuario_Semi] = 120    ' <eliminar> ::= ELIMINAR USUARIO <ID> ';'
        [Declarar_Declarar_Eq_Semi] = 121         ' <declarar> ::= DECLARAR <variables> <tipo_dato> '=' <expresion> ';'
        [Declarar_Declarar_Semi] = 122            ' <declarar> ::= DECLARAR <variables> <ID> ';'
        [Declarar_Declarar_Semi2] = 123           ' <declarar> ::= DECLARAR <variables> <tipo_dato> ';'
        [Variables_Variable_Comma] = 124          ' <variables> ::= Variable ',' <variables>
        [Variables_Variable] = 125                ' <variables> ::= Variable
        [Asignacion_Eq_Semi] = 126                ' <asignacion> ::= <rutaB> '=' <aritemtica> ';'
        [Asignacion_Variable_Eq_Semi] = 127       ' <asignacion> ::= Variable '=' <aritemtica> ';'
        [Tif_Si_Lparen_Rparen_Lbrace_Rbrace] = 128 ' <Tif> ::= SI '(' <logica> ')' '{' <instrucciones> '}' <sino>
        [Tif_Si_Lparen_Rparen_Lbrace_Rbrace2] = 129 ' <Tif> ::= SI '(' <logica> ')' '{' <instrucciones> '}'
        [Sino_Sino_Lbrace_Rbrace] = 130           ' <sino> ::= SINO '{' <instrucciones> '}'
        [Sino_Sino] = 131                         ' <sino> ::= SINO <Tif>
        [Tswitch_Selecciona_Lparen_Rparen_Lbrace_Rbrace] = 132 ' <Tswitch> ::= SELECCIONA '(' <expresion> ')' '{' <casos> '}'
        [Casos] = 133                             ' <casos> ::= <caso> <casos>
        [Casos2] = 134                            ' <casos> ::= <caso>
        [Casos3] = 135                            ' <casos> ::= <defecto>
        [Caso_Caso_Colon] = 136                   ' <caso> ::= CASO <expresion> ':' <instrucciones>
        [Defecto_Defecto_Colon] = 137             ' <defecto> ::= DEFECTO ':' <instrucciones>
        [Tfor_Para_Lparen_Declarar_Variable_Integer_Eq_Semi_Semi_Rparen_Lbrace_Rbrace] = 138 ' <Tfor> ::= PARA '(' DECLARAR Variable INTEGER '=' <expresion> ';' <logica> ';' <opciones_for> ')' '{' <instrucciones> '}'
        [Opciones_for_Plusplus] = 139             ' <opciones_for> ::= '++'
        [Opciones_for_Minusminus] = 140           ' <opciones_for> ::= '--'
        [Twhile_Mientras_Lparen_Rparen_Lbrace_Rbrace] = 141 ' <Twhile> ::= MIENTRAS '(' <logica> ')' '{' <instrucciones> '}'
        [Contar_Contar_Lparen_Ltlt_Gtgt_Rparen_Semi] = 142 ' <contar> ::= CONTAR '(' '<<' <seleccionarf> '>>' ')' ';'
        [Contarasig_Contar_Lparen_Ltlt_Gtgt_Rparen] = 143 ' <contarAsig> ::= CONTAR '(' '<<' <seleccionarf> '>>' ')'
        [Tipo_dato_Integer] = 144                 ' <tipo_dato> ::= INTEGER
        [Tipo_dato_Text] = 145                    ' <tipo_dato> ::= TEXT
        [Tipo_dato_Double] = 146                  ' <tipo_dato> ::= DOUBLE
        [Tipo_dato_Bool] = 147                    ' <tipo_dato> ::= BOOL
        [Tipo_dato_Date] = 148                    ' <tipo_dato> ::= DATE
        [Tipo_dato_Datetime] = 149                ' <tipo_dato> ::= DATETIME
        [Logica_Pipepipe] = 150                   ' <logica> ::= <logica> '||' <relacional>
        [Logica_Ampamp] = 151                     ' <logica> ::= <logica> '&&' <relacional>
        [Logica_Exclam] = 152                     ' <logica> ::= '!' <logica>
        [Logica_Lparen_Rparen] = 153              ' <logica> ::= '(' <logica> ')'
        [Logica] = 154                            ' <logica> ::= <relacional>
        [Relacional_Eqeq] = 155                   ' <relacional> ::= <relacional> '==' <aritemtica>
        [Relacional_Exclameq] = 156               ' <relacional> ::= <relacional> '!=' <aritemtica>
        [Relacional_Lteq] = 157                   ' <relacional> ::= <relacional> '<=' <aritemtica>
        [Relacional_Gteq] = 158                   ' <relacional> ::= <relacional> '>=' <aritemtica>
        [Relacional_Lt] = 159                     ' <relacional> ::= <relacional> '<' <aritemtica>
        [Relacional_Gt] = 160                     ' <relacional> ::= <relacional> '>' <aritemtica>
        [Relacional_Lparen_Rparen] = 161          ' <relacional> ::= '(' <relacional> ')'
        [Relacional] = 162                        ' <relacional> ::= <aritemtica>
        [Aritemtica_Plus] = 163                   ' <aritemtica> ::= <aritemtica> '+' <expresion>
        [Aritemtica_Minus] = 164                  ' <aritemtica> ::= <aritemtica> '-' <expresion>
        [Aritemtica_Times] = 165                  ' <aritemtica> ::= <aritemtica> '*' <expresion>
        [Aritemtica_Div] = 166                    ' <aritemtica> ::= <aritemtica> '/' <expresion>
        [Aritemtica_Caret] = 167                  ' <aritemtica> ::= <aritemtica> '^' <expresion>
        [Aritemtica_Lparen_Rparen] = 168          ' <aritemtica> ::= '(' <aritemtica> ')'
        [Aritemtica_Minus2] = 169                 ' <aritemtica> ::= '-' <expresion>
        [Aritemtica] = 170                        ' <aritemtica> ::= <expresion>
        [Expresion_Entero] = 171                  ' <expresion> ::= Entero
        [Expresion_Cadena] = 172                  ' <expresion> ::= Cadena
        [Expresion_Fecha] = 173                   ' <expresion> ::= Fecha
        [Expresion_Fechahora] = 174               ' <expresion> ::= FechaHora
        [Expresion_Doble] = 175                   ' <expresion> ::= Doble
        [Expresion] = 176                         ' <expresion> ::= <llamada>
        [Expresion2] = 177                        ' <expresion> ::= <contarAsig>
        [Expresion3] = 178                        ' <expresion> ::= <campos>
        [Llamada_Fecha_Lparen_Rparen] = 179       ' <llamada> ::= Fecha '(' ')'
        [Llamada_Fecha_hora_Lparen_Rparen] = 180  ' <llamada> ::= 'FECHA_HORA' '(' ')'
        [Llamada_Lparen_Rparen] = 181             ' <llamada> ::= <rutaB> '(' ')'
        [Llamada_Lparen_Rparen2] = 182            ' <llamada> ::= <rutaB> '(' <valores> ')'
        [Logica_consultas_En] = 183               ' <logica_consultas> ::= <logica_consulta> EN <logica_consultas>
        [Logica_consultas] = 184                  ' <logica_consultas> ::= <logica_consulta>
        [Logica_consulta_Lparen_Rparen] = 185     ' <logica_consulta> ::= '(' <seleccionar> ')'
        [Logica_consulta] = 186                   ' <logica_consulta> ::= <logica>
        [Id_Identificador] = 187                  ' <ID> ::= identificador
        [Rno_No] = 188                            ' <RNO> ::= NO
        [Rnulo_Nulo] = 189                        ' <RNULO> ::= Nulo
    End Enum

    Public Program As Object     'You might derive a specific object

    Public Sub Setup()
        'This procedure can be called to load the parse tables. The class can
        'read tables using a BinaryReader.
        
        Parser.LoadTables(Path.Combine(Application.StartupPath, "grammar.egt"))
    End Sub
    
    Public Function Parse(ByVal Reader As TextReader) As Boolean
        'This procedure starts the GOLD Parser Engine and handles each of the
        'messages it returns. Each time a reduction is made, you can create new
        'custom object and reassign the .CurrentReduction property. Otherwise, 
        'the system will use the Reduction object that was returned.
        '
        'The resulting tree will be a pure representation of the language 
        'and will be ready to implement.

        Dim Response As GOLD.ParseMessage
        Dim Done as Boolean                  'Controls when we leave the loop
        Dim Accepted As Boolean = False      'Was the parse successful?

        Accepted = False    'Unless the program is accepted by the parser

        Parser.Open(Reader)
        Parser.TrimReductions = False  'Please read about this feature before enabling  

        Done = False
        Do Until Done
            Response = Parser.Parse()

            Select Case Response              
                Case GOLD.ParseMessage.LexicalError
                    'Cannot recognize token
                    Done = True

                Case GOLD.ParseMessage.SyntaxError
                    'Expecting a different token
                    Done = True

                Case GOLD.ParseMessage.Reduction
                    'Create a customized object to store the reduction
                    .CurrentReduction = CreateNewObject(Parser.CurrentReduction)

                Case GOLD.ParseMessage.Accept
                    'Accepted!
                    'Program = Parser.CurrentReduction  'The root node!                 
                    Done = True
                    Accepted = True

                Case GOLD.ParseMessage.TokenRead
                    'You don't have to do anything here.

                Case GOLD.ParseMessage.InternalError
                    'INTERNAL ERROR! Something is horribly wrong.
                    Done = True

                Case GOLD.ParseMessage.NotLoadedError
                    'This error occurs if the CGT was not loaded.                   
                    Done = True

                Case GOLD.ParseMessage.GroupError 
                    'COMMENT ERROR! Unexpected end of file
                    Done = True
            End Select
        Loop

        Return Accepted
    End Function

    Private Function CreateNewObject(Reduction as GOLD.Reduction) As Object
        Dim Result As Object = Nothing

        With Reduction
            Select Case .Parent.TableIndex                        
                Case ProductionIndex.S                 
                    ' <S> ::= <Inicio> 

                Case ProductionIndex.Inicio                 
                    ' <Inicio> ::= <sentencias> 

                Case ProductionIndex.Sentencias                 
                    ' <sentencias> ::= <sentencia> <sentencias> 

                Case ProductionIndex.Sentencias2                 
                    ' <sentencias> ::= <sentencia> 

                Case ProductionIndex.Sentencia                 
                    ' <sentencia> ::= <usar> 

                Case ProductionIndex.Sentencia2                 
                    ' <sentencia> ::= <crear> 

                Case ProductionIndex.Sentencia3                 
                    ' <sentencia> ::= <imprimir> 

                Case ProductionIndex.Sentencia4                 
                    ' <sentencia> ::= <insertar> 

                Case ProductionIndex.Sentencia5                 
                    ' <sentencia> ::= <actualizar> 

                Case ProductionIndex.Sentencia6                 
                    ' <sentencia> ::= <borrar> 

                Case ProductionIndex.Sentencia7                 
                    ' <sentencia> ::= <seleccionar> 

                Case ProductionIndex.Sentencia8                 
                    ' <sentencia> ::= <otorgar> 

                Case ProductionIndex.Sentencia9                 
                    ' <sentencia> ::= <denegar> 

                Case ProductionIndex.Sentencia10                 
                    ' <sentencia> ::= <back> 

                Case ProductionIndex.Sentencia11                 
                    ' <sentencia> ::= <restaurar> 

                Case ProductionIndex.Sentencia12                 
                    ' <sentencia> ::= <alterar> 

                Case ProductionIndex.Sentencia13                 
                    ' <sentencia> ::= <eliminar> 

                Case ProductionIndex.Sentencia14                 
                    ' <sentencia> ::= <declarar> 

                Case ProductionIndex.Sentencia_Semi                 
                    ' <sentencia> ::= <llamada> ';' 

                Case ProductionIndex.Usar_Usar_Semi                 
                    ' <usar> ::= USAR <ID> ';' 

                Case ProductionIndex.Crear_Crear                 
                    ' <crear> ::= CREAR <opciones_c> 

                Case ProductionIndex.Opciones_c                 
                    ' <opciones_c> ::= <c_base> 

                Case ProductionIndex.Opciones_c2                 
                    ' <opciones_c> ::= <c_tabla> 

                Case ProductionIndex.Opciones_c3                 
                    ' <opciones_c> ::= <c_objeto> 

                Case ProductionIndex.Opciones_c4                 
                    ' <opciones_c> ::= <c_pro> 

                Case ProductionIndex.Opciones_c5                 
                    ' <opciones_c> ::= <c_funcion> 

                Case ProductionIndex.Opciones_c6                 
                    ' <opciones_c> ::= <c_usuario> 

                Case ProductionIndex.C_base_Base_datos_Semi                 
                    ' <c_base> ::= 'BASE_DATOS' <ID> ';' 

                Case ProductionIndex.C_tabla_Tabla_Lparen_Rparen_Semi                 
                    ' <c_tabla> ::= TABLA <ID> '(' <campos_tabla> ')' ';' 

                Case ProductionIndex.Campos_tabla_Comma                 
                    ' <campos_tabla> ::= <campo_tabla> ',' <campos_tabla> 

                Case ProductionIndex.Campos_tabla                 
                    ' <campos_tabla> ::= <campo_tabla> 

                Case ProductionIndex.Campo_tabla                 
                    ' <campo_tabla> ::= <tipo_dato> <ID> <complementos> 

                Case ProductionIndex.Campo_tabla2                 
                    ' <campo_tabla> ::= <tipo_dato> <ID> 

                Case ProductionIndex.Campo_tabla3                 
                    ' <campo_tabla> ::= <ID> <ID> <complementos> 

                Case ProductionIndex.Campo_tabla4                 
                    ' <campo_tabla> ::= <ID> <ID> 

                Case ProductionIndex.Complementos                 
                    ' <complementos> ::= <complemento> <complementos> 

                Case ProductionIndex.Complementos2                 
                    ' <complementos> ::= <complemento> 

                Case ProductionIndex.Complemento                 
                    ' <complemento> ::= <RNO> 

                Case ProductionIndex.Complemento2                 
                    ' <complemento> ::= <RNULO> 

                Case ProductionIndex.Complemento_Autoincrementable                 
                    ' <complemento> ::= Autoincrementable 

                Case ProductionIndex.Complemento_Llave_primaria                 
                    ' <complemento> ::= 'Llave_Primaria' 

                Case ProductionIndex.Complemento_Llave_foranea                 
                    ' <complemento> ::= 'Llave_Foranea' <ID> 

                Case ProductionIndex.Complemento_Unico                 
                    ' <complemento> ::= UNICO 

                Case ProductionIndex.C_objeto_Objeto_Lparen_Rparen_Semi                 
                    ' <c_objeto> ::= OBJETO <ID> '(' <parametros> ')' ';' 

                Case ProductionIndex.C_objeto_Objeto_Lparen_Rparen_Semi2                 
                    ' <c_objeto> ::= OBJETO <ID> '(' ')' ';' 

                Case ProductionIndex.Parametros_Comma                 
                    ' <parametros> ::= <parametros> ',' <parametro> 

                Case ProductionIndex.Parametros                 
                    ' <parametros> ::= <parametro> 

                Case ProductionIndex.Parametro                 
                    ' <parametro> ::= <tipo_dato> <ID> 

                Case ProductionIndex.Parametro_Variable                 
                    ' <parametro> ::= <tipo_dato> Variable 

                Case ProductionIndex.C_pro_Procedimiento_Lparen_Rparen_Lbrace_Rbrace                 
                    ' <c_pro> ::= PROCEDIMIENTO <ID> '(' <parametros> ')' '{' <instrucciones> '}' 

                Case ProductionIndex.C_pro_Procedimiento_Lparen_Rparen_Lbrace_Rbrace2                 
                    ' <c_pro> ::= PROCEDIMIENTO <ID> '(' ')' '{' <instrucciones> '}' 

                Case ProductionIndex.Instrucciones                 
                    ' <instrucciones> ::= <instruccion> <instrucciones> 

                Case ProductionIndex.Instrucciones2                 
                    ' <instrucciones> ::= <instruccion> 

                Case ProductionIndex.Instruccion                 
                    ' <instruccion> ::= <asignacion> 

                Case ProductionIndex.Instruccion2                 
                    ' <instruccion> ::= <Tif> 

                Case ProductionIndex.Instruccion3                 
                    ' <instruccion> ::= <Tswitch> 

                Case ProductionIndex.Instruccion4                 
                    ' <instruccion> ::= <Tfor> 

                Case ProductionIndex.Instruccion5                 
                    ' <instruccion> ::= <Twhile> 

                Case ProductionIndex.Instruccion6                 
                    ' <instruccion> ::= <sentencia> 

                Case ProductionIndex.Instruccion_Detener_Semi                 
                    ' <instruccion> ::= DETENER ';' 

                Case ProductionIndex.C_funcion_Funcion_Lparen_Rparen_Lbrace_Rbrace                 
                    ' <c_funcion> ::= FUNCION <ID> '(' <parametros> ')' <tipo_dato> '{' <instruccionesR> '}' 

                Case ProductionIndex.C_funcion_Funcion_Lparen_Rparen_Lbrace_Rbrace2                 
                    ' <c_funcion> ::= FUNCION <ID> '(' <parametros> ')' <ID> '{' <instruccionesR> '}' 

                Case ProductionIndex.C_funcion_Funcion_Lparen_Rparen_Lbrace_Rbrace3                 
                    ' <c_funcion> ::= FUNCION <ID> '(' ')' <tipo_dato> '{' <instruccionesR> '}' 

                Case ProductionIndex.C_funcion_Funcion_Lparen_Rparen_Lbrace_Rbrace4                 
                    ' <c_funcion> ::= FUNCION <ID> '(' ')' <ID> '{' <instruccionesR> '}' 

                Case ProductionIndex.Instruccionesr                 
                    ' <instruccionesR> ::= <instrucciones> <retorno> 

                Case ProductionIndex.Retorno_Retorno_Semi                 
                    ' <retorno> ::= RETORNO <aritemtica> ';' 

                Case ProductionIndex.C_usuario_Usuario_Colocar_Password_Eq_Cadena_Semi                 
                    ' <c_usuario> ::= USUARIO <ID> COLOCAR password '=' Cadena ';' 

                Case ProductionIndex.Imprimir_Imprimir_Lparen_Rparen_Semi                 
                    ' <imprimir> ::= IMPRIMIR '(' <expresion> ')' ';' 

                Case ProductionIndex.Insertar_Insertar_En_Tabla                 
                    ' <insertar> ::= INSERTAR EN TABLA <ID> <tipoins> 

                Case ProductionIndex.Tipoins_Lparen_Rparen_Valores_Lparen_Rparen_Semi                 
                    ' <tipoins> ::= '(' <campos> ')' VALORES '(' <valores> ')' ';' 

                Case ProductionIndex.Tipoins_Lparen_Rparen_Semi                 
                    ' <tipoins> ::= '(' <valores> ')' ';' 

                Case ProductionIndex.Campos_Comma                 
                    ' <campos> ::= <campos> ',' <rutaB> 

                Case ProductionIndex.Campos                 
                    ' <campos> ::= <rutaB> 

                Case ProductionIndex.Valores_Comma                 
                    ' <valores> ::= <aritemtica> ',' <valores> 

                Case ProductionIndex.Valores                 
                    ' <valores> ::= <aritemtica> 

                Case ProductionIndex.Actualizar_Actualizar_Tabla_Lparen_Rparen_Valores_Lparen_Rparen_Semi                 
                    ' <actualizar> ::= ACTUALIZAR TABLA <ID> '(' <campos> ')' VALORES '(' <valores> ')' <condicion> ';' 

                Case ProductionIndex.Actualizar_Actualizar_Tabla_Lparen_Rparen_Valores_Lparen_Rparen_Semi2                 
                    ' <actualizar> ::= ACTUALIZAR TABLA <ID> '(' <campos> ')' VALORES '(' <valores> ')' ';' 

                Case ProductionIndex.Condicion_Donde                 
                    ' <condicion> ::= DONDE <logica_consultas> 

                Case ProductionIndex.Borrar_Borrar_En_Tabla_Semi                 
                    ' <borrar> ::= BORRAR EN TABLA <ID> <condicion> ';' 

                Case ProductionIndex.Borrar_Borrar_En_Tabla_Semi2                 
                    ' <borrar> ::= BORRAR EN TABLA <ID> ';' 

                Case ProductionIndex.Seleccionar_Seleccionar_De_Semi                 
                    ' <seleccionar> ::= SELECCIONAR <campos> DE <campos> <condicion> <orden> ';' 

                Case ProductionIndex.Seleccionar_Seleccionar_Times_De_Semi                 
                    ' <seleccionar> ::= SELECCIONAR '*' DE <campos> <condicion> <orden> ';' 

                Case ProductionIndex.Seleccionar_Seleccionar_De_Semi2                 
                    ' <seleccionar> ::= SELECCIONAR <campos> DE <campos> <condicion> ';' 

                Case ProductionIndex.Seleccionar_Seleccionar_Times_De_Semi2                 
                    ' <seleccionar> ::= SELECCIONAR '*' DE <campos> <condicion> ';' 

                Case ProductionIndex.Seleccionar_Seleccionar_De_Semi3                 
                    ' <seleccionar> ::= SELECCIONAR <campos> DE <campos> <orden> ';' 

                Case ProductionIndex.Seleccionar_Seleccionar_Times_De_Semi3                 
                    ' <seleccionar> ::= SELECCIONAR '*' DE <campos> <orden> ';' 

                Case ProductionIndex.Seleccionar_Seleccionar_De_Semi4                 
                    ' <seleccionar> ::= SELECCIONAR <campos> DE <campos> ';' 

                Case ProductionIndex.Seleccionar_Seleccionar_Times_De_Semi4                 
                    ' <seleccionar> ::= SELECCIONAR '*' DE <campos> ';' 

                Case ProductionIndex.Seleccionarf_Seleccionar_De                 
                    ' <seleccionarf> ::= SELECCIONAR <campos> DE <campos> <condicion> <orden> 

                Case ProductionIndex.Seleccionarf_Seleccionar_Times_De                 
                    ' <seleccionarf> ::= SELECCIONAR '*' DE <campos> <condicion> <orden> 

                Case ProductionIndex.Seleccionarf_Seleccionar_De2                 
                    ' <seleccionarf> ::= SELECCIONAR <campos> DE <campos> <condicion> 

                Case ProductionIndex.Seleccionarf_Seleccionar_Times_De2                 
                    ' <seleccionarf> ::= SELECCIONAR '*' DE <campos> <condicion> 

                Case ProductionIndex.Seleccionarf_Seleccionar_De3                 
                    ' <seleccionarf> ::= SELECCIONAR <campos> DE <campos> <orden> 

                Case ProductionIndex.Seleccionarf_Seleccionar_Times_De3                 
                    ' <seleccionarf> ::= SELECCIONAR '*' DE <campos> <orden> 

                Case ProductionIndex.Seleccionarf_Seleccionar_De4                 
                    ' <seleccionarf> ::= SELECCIONAR <campos> DE <campos> 

                Case ProductionIndex.Seleccionarf_Seleccionar_Times_De4                 
                    ' <seleccionarf> ::= SELECCIONAR '*' DE <campos> 

                Case ProductionIndex.Orden_Ordenar_por_Asc                 
                    ' <orden> ::= 'ORDENAR_POR' <ID> ASC 

                Case ProductionIndex.Orden_Ordenar_por_Desc                 
                    ' <orden> ::= 'ORDENAR_POR' <ID> DESC 

                Case ProductionIndex.Orden_Ordenar_por                 
                    ' <orden> ::= 'ORDENAR_POR' <ID> 

                Case ProductionIndex.Otorgar_Otorgar_Permisos_Comma_Semi                 
                    ' <otorgar> ::= OTORGAR PERMISOS <ID> ',' <rutaB> ';' 

                Case ProductionIndex.Rutab_Dot                 
                    ' <rutaB> ::= <ID> '.' <rutaB> 

                Case ProductionIndex.Rutab_Variable_Dot                 
                    ' <rutaB> ::= Variable '.' <rutaB> 

                Case ProductionIndex.Rutab_Variable                 
                    ' <rutaB> ::= Variable 

                Case ProductionIndex.Rutab                 
                    ' <rutaB> ::= <ID> 

                Case ProductionIndex.Rutab_Times                 
                    ' <rutaB> ::= '*' 

                Case ProductionIndex.Denegar_Denegar_Permisos_Comma_Semi                 
                    ' <denegar> ::= DENEGAR PERMISOS <ID> ',' <rutaB> ';' 

                Case ProductionIndex.Back_Backup_Usqldump_Semi                 
                    ' <back> ::= BACKUP USQLDUMP <ID> <ID> ';' 

                Case ProductionIndex.Back_Backup_Completo_Semi                 
                    ' <back> ::= BACKUP COMPLETO <ID> <ID> ';' 

                Case ProductionIndex.Restaurar_Restaurar_Usqldump_Cadena_Semi                 
                    ' <restaurar> ::= RESTAURAR USQLDUMP Cadena ';' 

                Case ProductionIndex.Restaurar_Restaurar_Completo_Cadena_Semi                 
                    ' <restaurar> ::= RESTAURAR COMPLETO Cadena ';' 

                Case ProductionIndex.Alterar_Alterar_Tabla_Semi                 
                    ' <alterar> ::= ALTERAR TABLA <ID> <alterartabla> ';' 

                Case ProductionIndex.Alterar_Alterar_Objeto_Semi                 
                    ' <alterar> ::= ALTERAR OBJETO <ID> <alterarobjeto> ';' 

                Case ProductionIndex.Alterar_Alterar_Usuario_Cambiar_Password_Eq_Cadena                 
                    ' <alterar> ::= ALTERAR USUARIO <ID> CAMBIAR password '=' Cadena 

                Case ProductionIndex.Alterartabla_Agregar_Lparen_Rparen                 
                    ' <alterartabla> ::= AGREGAR '(' <campos_tabla> ')' 

                Case ProductionIndex.Alterartabla_Quitar                 
                    ' <alterartabla> ::= QUITAR <campos> 

                Case ProductionIndex.Alterarobjeto_Agregar_Lparen_Rparen                 
                    ' <alterarobjeto> ::= AGREGAR '(' <parametros> ')' 

                Case ProductionIndex.Alterarobjeto_Quitar                 
                    ' <alterarobjeto> ::= QUITAR <campos> 

                Case ProductionIndex.Eliminar_Eliminar_Tabla_Semi                 
                    ' <eliminar> ::= ELIMINAR TABLA <ID> ';' 

                Case ProductionIndex.Eliminar_Eliminar_Base_datos_Semi                 
                    ' <eliminar> ::= ELIMINAR 'BASE_DATOS' <ID> ';' 

                Case ProductionIndex.Eliminar_Eliminar_Objeto_Semi                 
                    ' <eliminar> ::= ELIMINAR OBJETO <ID> ';' 

                Case ProductionIndex.Eliminar_Eliminar_Usuario_Semi                 
                    ' <eliminar> ::= ELIMINAR USUARIO <ID> ';' 

                Case ProductionIndex.Declarar_Declarar_Eq_Semi                 
                    ' <declarar> ::= DECLARAR <variables> <tipo_dato> '=' <expresion> ';' 

                Case ProductionIndex.Declarar_Declarar_Semi                 
                    ' <declarar> ::= DECLARAR <variables> <ID> ';' 

                Case ProductionIndex.Declarar_Declarar_Semi2                 
                    ' <declarar> ::= DECLARAR <variables> <tipo_dato> ';' 

                Case ProductionIndex.Variables_Variable_Comma                 
                    ' <variables> ::= Variable ',' <variables> 

                Case ProductionIndex.Variables_Variable                 
                    ' <variables> ::= Variable 

                Case ProductionIndex.Asignacion_Eq_Semi                 
                    ' <asignacion> ::= <rutaB> '=' <aritemtica> ';' 

                Case ProductionIndex.Asignacion_Variable_Eq_Semi                 
                    ' <asignacion> ::= Variable '=' <aritemtica> ';' 

                Case ProductionIndex.Tif_Si_Lparen_Rparen_Lbrace_Rbrace                 
                    ' <Tif> ::= SI '(' <logica> ')' '{' <instrucciones> '}' <sino> 

                Case ProductionIndex.Tif_Si_Lparen_Rparen_Lbrace_Rbrace2                 
                    ' <Tif> ::= SI '(' <logica> ')' '{' <instrucciones> '}' 

                Case ProductionIndex.Sino_Sino_Lbrace_Rbrace                 
                    ' <sino> ::= SINO '{' <instrucciones> '}' 

                Case ProductionIndex.Sino_Sino                 
                    ' <sino> ::= SINO <Tif> 

                Case ProductionIndex.Tswitch_Selecciona_Lparen_Rparen_Lbrace_Rbrace                 
                    ' <Tswitch> ::= SELECCIONA '(' <expresion> ')' '{' <casos> '}' 

                Case ProductionIndex.Casos                 
                    ' <casos> ::= <caso> <casos> 

                Case ProductionIndex.Casos2                 
                    ' <casos> ::= <caso> 

                Case ProductionIndex.Casos3                 
                    ' <casos> ::= <defecto> 

                Case ProductionIndex.Caso_Caso_Colon                 
                    ' <caso> ::= CASO <expresion> ':' <instrucciones> 

                Case ProductionIndex.Defecto_Defecto_Colon                 
                    ' <defecto> ::= DEFECTO ':' <instrucciones> 

                Case ProductionIndex.Tfor_Para_Lparen_Declarar_Variable_Integer_Eq_Semi_Semi_Rparen_Lbrace_Rbrace                 
                    ' <Tfor> ::= PARA '(' DECLARAR Variable INTEGER '=' <expresion> ';' <logica> ';' <opciones_for> ')' '{' <instrucciones> '}' 

                Case ProductionIndex.Opciones_for_Plusplus                 
                    ' <opciones_for> ::= '++' 

                Case ProductionIndex.Opciones_for_Minusminus                 
                    ' <opciones_for> ::= '--' 

                Case ProductionIndex.Twhile_Mientras_Lparen_Rparen_Lbrace_Rbrace                 
                    ' <Twhile> ::= MIENTRAS '(' <logica> ')' '{' <instrucciones> '}' 

                Case ProductionIndex.Contar_Contar_Lparen_Ltlt_Gtgt_Rparen_Semi                 
                    ' <contar> ::= CONTAR '(' '<<' <seleccionarf> '>>' ')' ';' 

                Case ProductionIndex.Contarasig_Contar_Lparen_Ltlt_Gtgt_Rparen                 
                    ' <contarAsig> ::= CONTAR '(' '<<' <seleccionarf> '>>' ')' 

                Case ProductionIndex.Tipo_dato_Integer                 
                    ' <tipo_dato> ::= INTEGER 

                Case ProductionIndex.Tipo_dato_Text                 
                    ' <tipo_dato> ::= TEXT 

                Case ProductionIndex.Tipo_dato_Double                 
                    ' <tipo_dato> ::= DOUBLE 

                Case ProductionIndex.Tipo_dato_Bool                 
                    ' <tipo_dato> ::= BOOL 

                Case ProductionIndex.Tipo_dato_Date                 
                    ' <tipo_dato> ::= DATE 

                Case ProductionIndex.Tipo_dato_Datetime                 
                    ' <tipo_dato> ::= DATETIME 

                Case ProductionIndex.Logica_Pipepipe                 
                    ' <logica> ::= <logica> '||' <relacional> 

                Case ProductionIndex.Logica_Ampamp                 
                    ' <logica> ::= <logica> '&&' <relacional> 

                Case ProductionIndex.Logica_Exclam                 
                    ' <logica> ::= '!' <logica> 

                Case ProductionIndex.Logica_Lparen_Rparen                 
                    ' <logica> ::= '(' <logica> ')' 

                Case ProductionIndex.Logica                 
                    ' <logica> ::= <relacional> 

                Case ProductionIndex.Relacional_Eqeq                 
                    ' <relacional> ::= <relacional> '==' <aritemtica> 

                Case ProductionIndex.Relacional_Exclameq                 
                    ' <relacional> ::= <relacional> '!=' <aritemtica> 

                Case ProductionIndex.Relacional_Lteq                 
                    ' <relacional> ::= <relacional> '<=' <aritemtica> 

                Case ProductionIndex.Relacional_Gteq                 
                    ' <relacional> ::= <relacional> '>=' <aritemtica> 

                Case ProductionIndex.Relacional_Lt                 
                    ' <relacional> ::= <relacional> '<' <aritemtica> 

                Case ProductionIndex.Relacional_Gt                 
                    ' <relacional> ::= <relacional> '>' <aritemtica> 

                Case ProductionIndex.Relacional_Lparen_Rparen                 
                    ' <relacional> ::= '(' <relacional> ')' 

                Case ProductionIndex.Relacional                 
                    ' <relacional> ::= <aritemtica> 

                Case ProductionIndex.Aritemtica_Plus                 
                    ' <aritemtica> ::= <aritemtica> '+' <expresion> 

                Case ProductionIndex.Aritemtica_Minus                 
                    ' <aritemtica> ::= <aritemtica> '-' <expresion> 

                Case ProductionIndex.Aritemtica_Times                 
                    ' <aritemtica> ::= <aritemtica> '*' <expresion> 

                Case ProductionIndex.Aritemtica_Div                 
                    ' <aritemtica> ::= <aritemtica> '/' <expresion> 

                Case ProductionIndex.Aritemtica_Caret                 
                    ' <aritemtica> ::= <aritemtica> '^' <expresion> 

                Case ProductionIndex.Aritemtica_Lparen_Rparen                 
                    ' <aritemtica> ::= '(' <aritemtica> ')' 

                Case ProductionIndex.Aritemtica_Minus2                 
                    ' <aritemtica> ::= '-' <expresion> 

                Case ProductionIndex.Aritemtica                 
                    ' <aritemtica> ::= <expresion> 

                Case ProductionIndex.Expresion_Entero                 
                    ' <expresion> ::= Entero 

                Case ProductionIndex.Expresion_Cadena                 
                    ' <expresion> ::= Cadena 

                Case ProductionIndex.Expresion_Fecha                 
                    ' <expresion> ::= Fecha 

                Case ProductionIndex.Expresion_Fechahora                 
                    ' <expresion> ::= FechaHora 

                Case ProductionIndex.Expresion_Doble                 
                    ' <expresion> ::= Doble 

                Case ProductionIndex.Expresion                 
                    ' <expresion> ::= <llamada> 

                Case ProductionIndex.Expresion2                 
                    ' <expresion> ::= <contarAsig> 

                Case ProductionIndex.Expresion3                 
                    ' <expresion> ::= <campos> 

                Case ProductionIndex.Llamada_Fecha_Lparen_Rparen                 
                    ' <llamada> ::= Fecha '(' ')' 

                Case ProductionIndex.Llamada_Fecha_hora_Lparen_Rparen                 
                    ' <llamada> ::= 'FECHA_HORA' '(' ')' 

                Case ProductionIndex.Llamada_Lparen_Rparen                 
                    ' <llamada> ::= <rutaB> '(' ')' 

                Case ProductionIndex.Llamada_Lparen_Rparen2                 
                    ' <llamada> ::= <rutaB> '(' <valores> ')' 

                Case ProductionIndex.Logica_consultas_En                 
                    ' <logica_consultas> ::= <logica_consulta> EN <logica_consultas> 

                Case ProductionIndex.Logica_consultas                 
                    ' <logica_consultas> ::= <logica_consulta> 

                Case ProductionIndex.Logica_consulta_Lparen_Rparen                 
                    ' <logica_consulta> ::= '(' <seleccionar> ')' 

                Case ProductionIndex.Logica_consulta                 
                    ' <logica_consulta> ::= <logica> 

                Case ProductionIndex.Id_Identificador                 
                    ' <ID> ::= identificador 

                Case ProductionIndex.Rno_No                 
                    ' <RNO> ::= NO 

                Case ProductionIndex.Rnulo_Nulo                 
                    ' <RNULO> ::= Nulo 

            End Select
        End With     

        Return Result
    End Function
End Module
