'Generated by the GOLD Parser Builder

Option Explicit On
Option Strict Off

Imports System.IO
Imports System.Windows.Forms


Module MyParser
    Private Parser As New GOLD.Parser

    Private Enum SymbolIndex
        [Eof] = 0                                 ' (EOF)
        [Error] = 1                               ' (Error)
        [Comment] = 2                             ' Comment
        [Whitespace] = 3                          ' Whitespace
        [Ltexclamminusminus] = 4                  ' '<!--'
        [Minusminusgt] = 5                        ' '-->'
        [Apost] = 6                               ' ''
        [Ltexclamdoctype] = 7                     ' '<!doctype'
        [Ltdivagt] = 8                            ' '</a>'
        [Ltdivaddressgt] = 9                      ' '</address>'
        [Ltdivappletgt] = 10                      ' '</applet>'
        [Ltdivbgt] = 11                           ' '</b>'
        [Ltdivbiggt] = 12                         ' '</big>'
        [Ltdivblockquotegt] = 13                  ' '</blockquote>'
        [Ltdivbodygt] = 14                        ' '</body>'
        [Ltdivcaptiongt] = 15                     ' '</caption>'
        [Ltdivcentergt] = 16                      ' '</center>'
        [Ltdivcitegt] = 17                        ' '</cite>'
        [Ltdivcodegt] = 18                        ' '</code>'
        [Ltdivddgt] = 19                          ' '</dd>'
        [Ltdivdirgt] = 20                         ' '</dir>'
        [Ltdivdivgt] = 21                         ' '</div>'
        [Ltdivdlgt] = 22                          ' '</dl>'
        [Ltdivdtgt] = 23                          ' '</dt>'
        [Ltdivemgt] = 24                          ' '</em>'
        [Ltdivfontgt] = 25                        ' '</font>'
        [Ltdivformgt] = 26                        ' '</form>'
        [Ltdivh1gt] = 27                          ' '</h1>'
        [Ltdivh2gt] = 28                          ' '</h2>'
        [Ltdivh3gt] = 29                          ' '</h3>'
        [Ltdivh4gt] = 30                          ' '</h4>'
        [Ltdivh5gt] = 31                          ' '</h5>'
        [Ltdivh6gt] = 32                          ' '</h6>'
        [Ltdivheadgt] = 33                        ' '</head>'
        [Ltdivhtmlgt] = 34                        ' '</html>'
        [Ltdivigt] = 35                           ' '</i>'
        [Ltdivkbdgt] = 36                         ' '</kbd>'
        [Ltdivligt] = 37                          ' '</li>'
        [Ltdivmapgt] = 38                         ' '</map>'
        [Ltdivmenugt] = 39                        ' '</menu>'
        [Ltdivobjectgt] = 40                      ' '</object>'
        [Ltdivolgt] = 41                          ' '</ol>'
        [Ltdivpgt] = 42                           ' '</p>'
        [Ltdivsampgt] = 43                        ' '</samp>'
        [Ltdivscriptgt] = 44                      ' '</script>'
        [Ltdivselectgt] = 45                      ' '</select>'
        [Ltdivsmallgt] = 46                       ' '</small>'
        [Ltdivspangt] = 47                        ' '</span>'
        [Ltdivstrikegt] = 48                      ' '</strike>'
        [Ltdivstronggt] = 49                      ' '</strong>'
        [Ltdivsubgt] = 50                         ' '</sub>'
        [Ltdivsupgt] = 51                         ' '</sup>'
        [Ltdivtablegt] = 52                       ' '</table>'
        [Ltdivtdgt] = 53                          ' '</td>'
        [Ltdivtextareagt] = 54                    ' '</textarea>'
        [Ltdivthgt] = 55                          ' '</th>'
        [Ltdivtitlegt] = 56                       ' '</title>'
        [Ltdivtrgt] = 57                          ' '</tr>'
        [Ltdivttgt] = 58                          ' '</tt>'
        [Ltdivugt] = 59                           ' '</u>'
        [Ltdivulgt] = 60                          ' '</ul>'
        [Ltdivusqlgt] = 61                        ' '</USQL>'
        [Lta] = 62                                ' '<a'
        [Ltaddress] = 63                          ' '<address'
        [Ltapplet] = 64                           ' '<applet'
        [Ltarea] = 65                             ' '<area'
        [Ltb] = 66                                ' '<b'
        [Ltbase] = 67                             ' '<base'
        [Ltbasefont] = 68                         ' '<basefont'
        [Ltbig] = 69                              ' '<big'
        [Ltblockquote] = 70                       ' '<blockquote'
        [Ltbody] = 71                             ' '<body'
        [Ltbr] = 72                               ' '<br'
        [Ltcaption] = 73                          ' '<caption'
        [Ltcenter] = 74                           ' '<center'
        [Ltcite] = 75                             ' '<cite'
        [Ltcode] = 76                             ' '<code'
        [Ltdd] = 77                               ' '<dd'
        [Ltdir] = 78                              ' '<dir'
        [Ltdiv] = 79                              ' '<div'
        [Ltdl] = 80                               ' '<dl'
        [Ltdt] = 81                               ' '<dt'
        [Ltem] = 82                               ' '<em'
        [Ltfont] = 83                             ' '<font'
        [Ltform] = 84                             ' '<form'
        [Lth1] = 85                               ' '<h1'
        [Lth2] = 86                               ' '<h2'
        [Lth3] = 87                               ' '<h3'
        [Lth4] = 88                               ' '<h4'
        [Lth5] = 89                               ' '<h5'
        [Lth6] = 90                               ' '<h6'
        [Lthead] = 91                             ' '<head'
        [Lthr] = 92                               ' '<hr'
        [Lthtml] = 93                             ' '<html'
        [Lti] = 94                                ' '<i'
        [Ltimg] = 95                              ' '<img'
        [Ltinput] = 96                            ' '<input'
        [Ltkbd] = 97                              ' '<kbd'
        [Ltli] = 98                               ' '<li'
        [Ltlink] = 99                             ' '<link'
        [Ltmap] = 100                             ' '<map'
        [Ltmenu] = 101                            ' '<menu'
        [Ltmeta] = 102                            ' '<meta'
        [Ltobject] = 103                          ' '<object'
        [Ltol] = 104                              ' '<ol'
        [Ltoption] = 105                          ' '<option'
        [Ltp] = 106                               ' '<p'
        [Ltparam] = 107                           ' '<param'
        [Ltsamp] = 108                            ' '<samp'
        [Ltscript] = 109                          ' '<script'
        [Ltselect] = 110                          ' '<select'
        [Ltsmall] = 111                           ' '<small'
        [Ltspan] = 112                            ' '<span'
        [Ltstrike] = 113                          ' '<strike'
        [Ltstrong] = 114                          ' '<strong'
        [Ltsub] = 115                             ' '<sub'
        [Ltsup] = 116                             ' '<sup'
        [Lttable] = 117                           ' '<table'
        [Lttd] = 118                              ' '<td'
        [Lttextarea] = 119                        ' '<textarea'
        [Ltth] = 120                              ' '<th'
        [Lttitle] = 121                           ' '<title'
        [Lttr] = 122                              ' '<tr'
        [Lttt] = 123                              ' '<tt'
        [Ltu] = 124                               ' '<u'
        [Ltul] = 125                              ' '<ul'
        [Ltusql] = 126                            ' '<USQL'
        [Eq] = 127                                ' '='
        [Gt] = 128                                ' '>'
        [Charname] = 129                          ' CharName
        [Charnumber] = 130                        ' CharNumber
        [Color] = 131                             ' Color
        [Id] = 132                                ' ID
        [Stringliteral] = 133                     ' StringLiteral
        [Symbol] = 134                            ' Symbol
        [Area] = 135                              ' <Area>
        [Body] = 136                              ' <Body>
        [Content] = 137                           ' <Content>
        [Defitem] = 138                           ' <Def Item>
        [Defitems] = 139                          ' <Def Items>
        [Doctypeopt] = 140                        ' <DocType Opt>
        [Head] = 141                              ' <Head>
        [Headitem] = 142                          ' <Head Item>
        [Headitems] = 143                         ' <Head Items>
        [Html] = 144                              ' <HTML>
        [Listitem] = 145                          ' <List Item>
        [Listitems] = 146                         ' <List Items>
        [Mapitems] = 147                          ' <Map Items>
        [Option] = 148                            ' <Option>
        [Options] = 149                           ' <Options>
        [Pcontent] = 150                          ' <P Content>
        [Parameter] = 151                         ' <Parameter>
        [Parameters] = 152                        ' <Parameters>
        [Params] = 153                            ' <Params>
        [Tablecell] = 154                         ' <Table Cell>
        [Tablecells] = 155                        ' <Table Cells>
        [Tablerows] = 156                         ' <Table Rows>
        [Tag] = 157                               ' <Tag>
        [Webpagebody] = 158                       ' <Webpage Body>
        [Word] = 159                              ' <Word>
    End Enum

    Private Enum ProductionIndex
        [Html_Lthtml_Gt_Ltdivhtmlgt] = 0          ' <HTML> ::= <DocType Opt> '<html' <Parameters> '>' <Webpage Body> '</html>'
        [Doctypeopt_Ltexclamdoctype_Gt] = 1       ' <DocType Opt> ::= '<!doctype' <Parameters> '>'
        [Doctypeopt] = 2                          ' <DocType Opt> ::= 
        [Webpagebody] = 3                         ' <Webpage Body> ::= <Head> <Body>
        [Head_Lthead_Gt_Ltdivheadgt] = 4          ' <Head> ::= '<head' <Parameters> '>' <Head Items> '</head>'
        [Head] = 5                                ' <Head> ::= 
        [Headitems] = 6                           ' <Head Items> ::= <Head Item> <Head Items>
        [Headitems2] = 7                          ' <Head Items> ::= 
        [Headitem_Lttitle_Gt_Ltdivtitlegt] = 8    ' <Head Item> ::= '<title' <Parameters> '>' <Content> '</title>'
        [Headitem_Ltmeta_Gt] = 9                  ' <Head Item> ::= '<meta' <Parameters> '>'
        [Headitem_Ltlink_Gt] = 10                 ' <Head Item> ::= '<link' <Parameters> '>'
        [Headitem_Ltbase_Gt] = 11                 ' <Head Item> ::= '<base' <Parameters> '>'
        [Headitem_Ltbasefont_Gt] = 12             ' <Head Item> ::= '<basefont' <Parameters> '>'
        [Headitem_Ltscript_Gt_Ltdivscriptgt] = 13 ' <Head Item> ::= '<script' <Parameters> '>' <Content> '</script>'
        [Body_Ltbody_Gt_Ltdivbodygt] = 14         ' <Body> ::= '<body' <Parameters> '>' <Content> '</body>'
        [Content_Ltp_Gt] = 15                     ' <Content> ::= '<p' <Parameters> '>' <P Content>
        [Content] = 16                            ' <Content> ::= <Tag> <Content>
        [Content2] = 17                           ' <Content> ::= <Word> <Content>
        [Content3] = 18                           ' <Content> ::= 
        [Pcontent] = 19                           ' <P Content> ::= <Tag> <P Content>
        [Pcontent2] = 20                          ' <P Content> ::= <Word> <P Content>
        [Pcontent3] = 21                          ' <P Content> ::= 
        [Parameters] = 22                         ' <Parameters> ::= <Parameter> <Parameters>
        [Parameters2] = 23                        ' <Parameters> ::= 
        [Parameter_Id_Eq_Stringliteral] = 24      ' <Parameter> ::= ID '=' StringLiteral
        [Parameter_Id_Eq_Color] = 25              ' <Parameter> ::= ID '=' Color
        [Parameter_Id_Eq_Id] = 26                 ' <Parameter> ::= ID '=' ID
        [Parameter_Id] = 27                       ' <Parameter> ::= ID
        [Parameter_Stringliteral] = 28            ' <Parameter> ::= StringLiteral
        [Tag_Ltimg_Gt] = 29                       ' <Tag> ::= '<img' <Parameters> '>'
        [Tag_Ltbr_Gt] = 30                        ' <Tag> ::= '<br' <Parameters> '>'
        [Tag_Lthr_Gt] = 31                        ' <Tag> ::= '<hr' <Parameters> '>'
        [Tag_Ltp_Gt_Ltdivpgt] = 32                ' <Tag> ::= '<p' <Parameters> '>' <P Content> '</p>'
        [Tag_Lth1_Gt_Ltdivh1gt] = 33              ' <Tag> ::= '<h1' <Parameters> '>' <Content> '</h1>'
        [Tag_Lth2_Gt_Ltdivh2gt] = 34              ' <Tag> ::= '<h2' <Parameters> '>' <Content> '</h2>'
        [Tag_Lth3_Gt_Ltdivh3gt] = 35              ' <Tag> ::= '<h3' <Parameters> '>' <Content> '</h3>'
        [Tag_Lth4_Gt_Ltdivh4gt] = 36              ' <Tag> ::= '<h4' <Parameters> '>' <Content> '</h4>'
        [Tag_Lth5_Gt_Ltdivh5gt] = 37              ' <Tag> ::= '<h5' <Parameters> '>' <Content> '</h5>'
        [Tag_Lth6_Gt_Ltdivh6gt] = 38              ' <Tag> ::= '<h6' <Parameters> '>' <Content> '</h6>'
        [Tag_Lta_Gt_Ltdivagt] = 39                ' <Tag> ::= '<a' <Parameters> '>' <Content> '</a>'
        [Tag_Ltmap_Gt_Ltdivmapgt] = 40            ' <Tag> ::= '<map' <Parameters> '>' <Map Items> '</map>'
        [Tag_Ltb_Gt_Ltdivbgt] = 41                ' <Tag> ::= '<b' <Parameters> '>' <Content> '</b>'
        [Tag_Ltu_Gt_Ltdivugt] = 42                ' <Tag> ::= '<u' <Parameters> '>' <Content> '</u>'
        [Tag_Ltem_Gt_Ltdivemgt] = 43              ' <Tag> ::= '<em' <Parameters> '>' <Content> '</em>'
        [Tag_Lti_Gt_Ltdivigt] = 44                ' <Tag> ::= '<i' <Parameters> '>' <Content> '</i>'
        [Tag_Ltstrike_Gt_Ltdivstrikegt] = 45      ' <Tag> ::= '<strike' <Parameters> '>' <Content> '</strike>'
        [Tag_Ltstrong_Gt_Ltdivstronggt] = 46      ' <Tag> ::= '<strong' <Parameters> '>' <Content> '</strong>'
        [Tag_Ltfont_Gt_Ltdivfontgt] = 47          ' <Tag> ::= '<font' <Parameters> '>' <Content> '</font>'
        [Tag_Ltbig_Gt_Ltdivbiggt] = 48            ' <Tag> ::= '<big' <Parameters> '>' <Content> '</big>'
        [Tag_Ltsmall_Gt_Ltdivsmallgt] = 49        ' <Tag> ::= '<small' <Parameters> '>' <Content> '</small>'
        [Tag_Ltsup_Gt_Ltdivsupgt] = 50            ' <Tag> ::= '<sup' <Parameters> '>' <Content> '</sup>'
        [Tag_Ltsub_Gt_Ltdivsubgt] = 51            ' <Tag> ::= '<sub' <Parameters> '>' <Content> '</sub>'
        [Tag_Ltblockquote_Gt_Ltdivblockquotegt] = 52 ' <Tag> ::= '<blockquote' <Parameters> '>' <Content> '</blockquote>'
        [Tag_Ltaddress_Gt_Ltdivaddressgt] = 53    ' <Tag> ::= '<address' <Parameters> '>' <Content> '</address>'
        [Tag_Ltcode_Gt_Ltdivcodegt] = 54          ' <Tag> ::= '<code' <Parameters> '>' <Content> '</code>'
        [Tag_Ltcite_Gt_Ltdivcitegt] = 55          ' <Tag> ::= '<cite' <Parameters> '>' <Content> '</cite>'
        [Tag_Ltcaption_Gt_Ltdivcaptiongt] = 56    ' <Tag> ::= '<caption' <Parameters> '>' <Content> '</caption>'
        [Tag_Ltsamp_Gt_Ltdivsampgt] = 57          ' <Tag> ::= '<samp' <Parameters> '>' <Content> '</samp>'
        [Tag_Ltkbd_Gt_Ltdivkbdgt] = 58            ' <Tag> ::= '<kbd' <Parameters> '>' <Content> '</kbd>'
        [Tag_Lttt_Gt_Ltdivttgt] = 59              ' <Tag> ::= '<tt' <Parameters> '>' <Content> '</tt>'
        [Tag_Ltcenter_Gt_Ltdivcentergt] = 60      ' <Tag> ::= '<center' <Parameters> '>' <Content> '</center>'
        [Tag_Ltspan_Gt_Ltdivspangt] = 61          ' <Tag> ::= '<span' <Parameters> '>' <Content> '</span>'
        [Tag_Ltdiv_Gt_Ltdivdivgt] = 62            ' <Tag> ::= '<div' <Parameters> '>' <Content> '</div>'
        [Tag_Ltapplet_Gt_Ltdivappletgt] = 63      ' <Tag> ::= '<applet' <Parameters> '>' <Params> '</applet>'
        [Tag_Ltobject_Gt_Ltdivobjectgt] = 64      ' <Tag> ::= '<object' <Parameters> '>' <Params> '</object>'
        [Tag_Lttable_Gt_Ltdivtablegt] = 65        ' <Tag> ::= '<table' <Parameters> '>' <Table Rows> '</table>'
        [Tag_Ltul_Gt_Ltdivulgt] = 66              ' <Tag> ::= '<ul' <Parameters> '>' <List Items> '</ul>'
        [Tag_Ltol_Gt_Ltdivolgt] = 67              ' <Tag> ::= '<ol' <Parameters> '>' <List Items> '</ol>'
        [Tag_Ltdir_Gt_Ltdivdirgt] = 68            ' <Tag> ::= '<dir' <Parameters> '>' <List Items> '</dir>'
        [Tag_Ltmenu_Gt_Ltdivmenugt] = 69          ' <Tag> ::= '<menu' <Parameters> '>' <List Items> '</menu>'
        [Tag_Ltdl_Gt_Ltdivdlgt] = 70              ' <Tag> ::= '<dl' <Parameters> '>' <Def Items> '</dl>'
        [Tag_Ltform_Gt_Ltdivformgt] = 71          ' <Tag> ::= '<form' <Parameters> '>' <Content> '</form>'
        [Tag_Ltinput_Gt] = 72                     ' <Tag> ::= '<input' <Parameters> '>'
        [Tag_Ltselect_Gt_Ltdivselectgt] = 73      ' <Tag> ::= '<select' <Parameters> '>' <Options> '</select>'
        [Tag_Lttextarea_Gt_Ltdivtextareagt] = 74  ' <Tag> ::= '<textarea' <Parameters> '>' <Content> '</textarea>'
        [Tag_Ltusql_Gt_Ltdivusqlgt] = 75          ' <Tag> ::= '<USQL' <Parameters> '>' <Content> '</USQL>'
        [Tablerows_Lttr_Gt_Ltdivtrgt] = 76        ' <Table Rows> ::= '<tr' <Parameters> '>' <Table Cells> '</tr>' <Table Rows>
        [Tablerows] = 77                          ' <Table Rows> ::= 
        [Tablecells] = 78                         ' <Table Cells> ::= <Table Cell> <Table Cells>
        [Tablecells2] = 79                        ' <Table Cells> ::= 
        [Tablecell_Lttd_Gt_Ltdivtdgt] = 80        ' <Table Cell> ::= '<td' <Parameters> '>' <Content> '</td>'
        [Tablecell_Ltth_Gt_Ltdivthgt] = 81        ' <Table Cell> ::= '<th' <Parameters> '>' <Content> '</th>'
        [Defitems] = 82                           ' <Def Items> ::= <Def Item> <Def Items>
        [Defitems2] = 83                          ' <Def Items> ::= 
        [Defitem_Ltdt_Gt_Ltdivdtgt] = 84          ' <Def Item> ::= '<dt' <Parameters> '>' <Content> '</dt>'
        [Defitem_Ltdd_Gt_Ltdivddgt] = 85          ' <Def Item> ::= '<dd' <Parameters> '>' <Content> '</dd>'
        [Listitems] = 86                          ' <List Items> ::= <List Item> <List Items>
        [Listitems2] = 87                         ' <List Items> ::= 
        [Listitem_Ltli_Gt_Ltdivligt] = 88         ' <List Item> ::= '<li' <Parameters> '>' <Content> '</li>'
        [Options] = 89                            ' <Options> ::= <Option> <Options>
        [Options2] = 90                           ' <Options> ::= 
        [Option_Ltoption_Gt] = 91                 ' <Option> ::= '<option' <Parameters> '>'
        [Mapitems] = 92                           ' <Map Items> ::= <Area> <Map Items>
        [Mapitems2] = 93                          ' <Map Items> ::= 
        [Area_Ltarea_Gt] = 94                     ' <Area> ::= '<area' <Parameters> '>'
        [Params_Ltparam_Gt] = 95                  ' <Params> ::= '<param' <Parameters> '>' <Params>
        [Params] = 96                             ' <Params> ::= 
        [Word_Id] = 97                            ' <Word> ::= ID
        [Word_Symbol] = 98                        ' <Word> ::= Symbol
        [Word_Eq] = 99                            ' <Word> ::= '='
        [Word_Apost] = 100                        ' <Word> ::= ''
        [Word_Charname] = 101                     ' <Word> ::= CharName
        [Word_Charnumber] = 102                   ' <Word> ::= CharNumber
        [Word_Color] = 103                        ' <Word> ::= Color
    End Enum

    Public Program As Object     'You might derive a specific object

    Public Sub Setup()
        'This procedure can be called to load the parse tables. The class can
        'read tables using a BinaryReader.

        Parser.LoadTables(Path.Combine(Application.StartupPath, "HTML.egt"))
    End Sub
    
    Public Function Parse(ByVal Reader As TextReader) As Boolean
        'This procedure starts the GOLD Parser Engine and handles each of the
        'messages it returns. Each time a reduction is made, you can create new
        'custom object and reassign the .CurrentReduction property. Otherwise, 
        'the system will use the Reduction object that was returned.
        '
        'The resulting tree will be a pure representation of the language 
        'and will be ready to implement.

        Dim Response As GOLD.ParseMessage
        Dim Done as Boolean                  'Controls when we leave the loop
        Dim Accepted As Boolean = False      'Was the parse successful?

        Accepted = False    'Unless the program is accepted by the parser

        Parser.Open(Reader)
        Parser.TrimReductions = False  'Please read about this feature before enabling  

        Done = False
        Do Until Done
            Response = Parser.Parse()

            Select Case Response              
                Case GOLD.ParseMessage.LexicalError
                    'Cannot recognize token
                    Done = True

                Case GOLD.ParseMessage.SyntaxError
                    'Expecting a different token
                    Done = True

                Case GOLD.ParseMessage.Reduction
                    'Create a customized object to store the reduction
                    Parser.CurrentReduction = CreateNewObject(Parser.CurrentReduction)

                Case GOLD.ParseMessage.Accept
                    'Accepted!
                    'Program = Parser.CurrentReduction  'The root node!                 
                    Done = True
                    Accepted = True

                Case GOLD.ParseMessage.TokenRead
                    'You don't have to do anything here.

                Case GOLD.ParseMessage.InternalError
                    'INTERNAL ERROR! Something is horribly wrong.
                    Done = True

                Case GOLD.ParseMessage.NotLoadedError
                    'This error occurs if the CGT was not loaded.                   
                    Done = True

                Case GOLD.ParseMessage.GroupError 
                    'COMMENT ERROR! Unexpected end of file
                    Done = True
            End Select
        Loop

        Return Accepted
    End Function

    Private Function CreateNewObject(Reduction as GOLD.Reduction) As Object
        Dim Result As Object = Nothing

        With Reduction
            Select Case .Parent.TableIndex                        
                Case ProductionIndex.Html_Lthtml_Gt_Ltdivhtmlgt                 
                    ' <HTML> ::= <DocType Opt> '<html' <Parameters> '>' <Webpage Body> '</html>' 

                Case ProductionIndex.Doctypeopt_Ltexclamdoctype_Gt                 
                    ' <DocType Opt> ::= '<!doctype' <Parameters> '>' 

                Case ProductionIndex.Doctypeopt                 
                    ' <DocType Opt> ::=  

                Case ProductionIndex.Webpagebody                 
                    ' <Webpage Body> ::= <Head> <Body> 

                Case ProductionIndex.Head_Lthead_Gt_Ltdivheadgt                 
                    ' <Head> ::= '<head' <Parameters> '>' <Head Items> '</head>' 

                Case ProductionIndex.Head                 
                    ' <Head> ::=  

                Case ProductionIndex.Headitems                 
                    ' <Head Items> ::= <Head Item> <Head Items> 

                Case ProductionIndex.Headitems2                 
                    ' <Head Items> ::=  

                Case ProductionIndex.Headitem_Lttitle_Gt_Ltdivtitlegt                 
                    ' <Head Item> ::= '<title' <Parameters> '>' <Content> '</title>' 

                Case ProductionIndex.Headitem_Ltmeta_Gt                 
                    ' <Head Item> ::= '<meta' <Parameters> '>' 

                Case ProductionIndex.Headitem_Ltlink_Gt                 
                    ' <Head Item> ::= '<link' <Parameters> '>' 

                Case ProductionIndex.Headitem_Ltbase_Gt                 
                    ' <Head Item> ::= '<base' <Parameters> '>' 

                Case ProductionIndex.Headitem_Ltbasefont_Gt                 
                    ' <Head Item> ::= '<basefont' <Parameters> '>' 

                Case ProductionIndex.Headitem_Ltscript_Gt_Ltdivscriptgt                 
                    ' <Head Item> ::= '<script' <Parameters> '>' <Content> '</script>' 

                Case ProductionIndex.Body_Ltbody_Gt_Ltdivbodygt                 
                    ' <Body> ::= '<body' <Parameters> '>' <Content> '</body>' 

                Case ProductionIndex.Content_Ltp_Gt                 
                    ' <Content> ::= '<p' <Parameters> '>' <P Content> 

                Case ProductionIndex.Content                 
                    ' <Content> ::= <Tag> <Content> 

                Case ProductionIndex.Content2                 
                    ' <Content> ::= <Word> <Content> 

                Case ProductionIndex.Content3                 
                    ' <Content> ::=  

                Case ProductionIndex.Pcontent                 
                    ' <P Content> ::= <Tag> <P Content> 

                Case ProductionIndex.Pcontent2                 
                    ' <P Content> ::= <Word> <P Content> 

                Case ProductionIndex.Pcontent3                 
                    ' <P Content> ::=  

                Case ProductionIndex.Parameters                 
                    ' <Parameters> ::= <Parameter> <Parameters> 

                Case ProductionIndex.Parameters2                 
                    ' <Parameters> ::=  

                Case ProductionIndex.Parameter_Id_Eq_Stringliteral                 
                    ' <Parameter> ::= ID '=' StringLiteral 

                Case ProductionIndex.Parameter_Id_Eq_Color                 
                    ' <Parameter> ::= ID '=' Color 

                Case ProductionIndex.Parameter_Id_Eq_Id                 
                    ' <Parameter> ::= ID '=' ID 

                Case ProductionIndex.Parameter_Id                 
                    ' <Parameter> ::= ID 

                Case ProductionIndex.Parameter_Stringliteral                 
                    ' <Parameter> ::= StringLiteral 

                Case ProductionIndex.Tag_Ltimg_Gt                 
                    ' <Tag> ::= '<img' <Parameters> '>' 

                Case ProductionIndex.Tag_Ltbr_Gt                 
                    ' <Tag> ::= '<br' <Parameters> '>' 

                Case ProductionIndex.Tag_Lthr_Gt                 
                    ' <Tag> ::= '<hr' <Parameters> '>' 

                Case ProductionIndex.Tag_Ltp_Gt_Ltdivpgt                 
                    ' <Tag> ::= '<p' <Parameters> '>' <P Content> '</p>' 

                Case ProductionIndex.Tag_Lth1_Gt_Ltdivh1gt                 
                    ' <Tag> ::= '<h1' <Parameters> '>' <Content> '</h1>' 

                Case ProductionIndex.Tag_Lth2_Gt_Ltdivh2gt                 
                    ' <Tag> ::= '<h2' <Parameters> '>' <Content> '</h2>' 

                Case ProductionIndex.Tag_Lth3_Gt_Ltdivh3gt                 
                    ' <Tag> ::= '<h3' <Parameters> '>' <Content> '</h3>' 

                Case ProductionIndex.Tag_Lth4_Gt_Ltdivh4gt                 
                    ' <Tag> ::= '<h4' <Parameters> '>' <Content> '</h4>' 

                Case ProductionIndex.Tag_Lth5_Gt_Ltdivh5gt                 
                    ' <Tag> ::= '<h5' <Parameters> '>' <Content> '</h5>' 

                Case ProductionIndex.Tag_Lth6_Gt_Ltdivh6gt                 
                    ' <Tag> ::= '<h6' <Parameters> '>' <Content> '</h6>' 

                Case ProductionIndex.Tag_Lta_Gt_Ltdivagt                 
                    ' <Tag> ::= '<a' <Parameters> '>' <Content> '</a>' 

                Case ProductionIndex.Tag_Ltmap_Gt_Ltdivmapgt                 
                    ' <Tag> ::= '<map' <Parameters> '>' <Map Items> '</map>' 

                Case ProductionIndex.Tag_Ltb_Gt_Ltdivbgt                 
                    ' <Tag> ::= '<b' <Parameters> '>' <Content> '</b>' 

                Case ProductionIndex.Tag_Ltu_Gt_Ltdivugt                 
                    ' <Tag> ::= '<u' <Parameters> '>' <Content> '</u>' 

                Case ProductionIndex.Tag_Ltem_Gt_Ltdivemgt                 
                    ' <Tag> ::= '<em' <Parameters> '>' <Content> '</em>' 

                Case ProductionIndex.Tag_Lti_Gt_Ltdivigt                 
                    ' <Tag> ::= '<i' <Parameters> '>' <Content> '</i>' 

                Case ProductionIndex.Tag_Ltstrike_Gt_Ltdivstrikegt                 
                    ' <Tag> ::= '<strike' <Parameters> '>' <Content> '</strike>' 

                Case ProductionIndex.Tag_Ltstrong_Gt_Ltdivstronggt                 
                    ' <Tag> ::= '<strong' <Parameters> '>' <Content> '</strong>' 

                Case ProductionIndex.Tag_Ltfont_Gt_Ltdivfontgt                 
                    ' <Tag> ::= '<font' <Parameters> '>' <Content> '</font>' 

                Case ProductionIndex.Tag_Ltbig_Gt_Ltdivbiggt                 
                    ' <Tag> ::= '<big' <Parameters> '>' <Content> '</big>' 

                Case ProductionIndex.Tag_Ltsmall_Gt_Ltdivsmallgt                 
                    ' <Tag> ::= '<small' <Parameters> '>' <Content> '</small>' 

                Case ProductionIndex.Tag_Ltsup_Gt_Ltdivsupgt                 
                    ' <Tag> ::= '<sup' <Parameters> '>' <Content> '</sup>' 

                Case ProductionIndex.Tag_Ltsub_Gt_Ltdivsubgt                 
                    ' <Tag> ::= '<sub' <Parameters> '>' <Content> '</sub>' 

                Case ProductionIndex.Tag_Ltblockquote_Gt_Ltdivblockquotegt                 
                    ' <Tag> ::= '<blockquote' <Parameters> '>' <Content> '</blockquote>' 

                Case ProductionIndex.Tag_Ltaddress_Gt_Ltdivaddressgt                 
                    ' <Tag> ::= '<address' <Parameters> '>' <Content> '</address>' 

                Case ProductionIndex.Tag_Ltcode_Gt_Ltdivcodegt                 
                    ' <Tag> ::= '<code' <Parameters> '>' <Content> '</code>' 

                Case ProductionIndex.Tag_Ltcite_Gt_Ltdivcitegt                 
                    ' <Tag> ::= '<cite' <Parameters> '>' <Content> '</cite>' 

                Case ProductionIndex.Tag_Ltcaption_Gt_Ltdivcaptiongt                 
                    ' <Tag> ::= '<caption' <Parameters> '>' <Content> '</caption>' 

                Case ProductionIndex.Tag_Ltsamp_Gt_Ltdivsampgt                 
                    ' <Tag> ::= '<samp' <Parameters> '>' <Content> '</samp>' 

                Case ProductionIndex.Tag_Ltkbd_Gt_Ltdivkbdgt                 
                    ' <Tag> ::= '<kbd' <Parameters> '>' <Content> '</kbd>' 

                Case ProductionIndex.Tag_Lttt_Gt_Ltdivttgt                 
                    ' <Tag> ::= '<tt' <Parameters> '>' <Content> '</tt>' 

                Case ProductionIndex.Tag_Ltcenter_Gt_Ltdivcentergt                 
                    ' <Tag> ::= '<center' <Parameters> '>' <Content> '</center>' 

                Case ProductionIndex.Tag_Ltspan_Gt_Ltdivspangt                 
                    ' <Tag> ::= '<span' <Parameters> '>' <Content> '</span>' 

                Case ProductionIndex.Tag_Ltdiv_Gt_Ltdivdivgt                 
                    ' <Tag> ::= '<div' <Parameters> '>' <Content> '</div>' 

                Case ProductionIndex.Tag_Ltapplet_Gt_Ltdivappletgt                 
                    ' <Tag> ::= '<applet' <Parameters> '>' <Params> '</applet>' 

                Case ProductionIndex.Tag_Ltobject_Gt_Ltdivobjectgt                 
                    ' <Tag> ::= '<object' <Parameters> '>' <Params> '</object>' 

                Case ProductionIndex.Tag_Lttable_Gt_Ltdivtablegt                 
                    ' <Tag> ::= '<table' <Parameters> '>' <Table Rows> '</table>' 

                Case ProductionIndex.Tag_Ltul_Gt_Ltdivulgt                 
                    ' <Tag> ::= '<ul' <Parameters> '>' <List Items> '</ul>' 

                Case ProductionIndex.Tag_Ltol_Gt_Ltdivolgt                 
                    ' <Tag> ::= '<ol' <Parameters> '>' <List Items> '</ol>' 

                Case ProductionIndex.Tag_Ltdir_Gt_Ltdivdirgt                 
                    ' <Tag> ::= '<dir' <Parameters> '>' <List Items> '</dir>' 

                Case ProductionIndex.Tag_Ltmenu_Gt_Ltdivmenugt                 
                    ' <Tag> ::= '<menu' <Parameters> '>' <List Items> '</menu>' 

                Case ProductionIndex.Tag_Ltdl_Gt_Ltdivdlgt                 
                    ' <Tag> ::= '<dl' <Parameters> '>' <Def Items> '</dl>' 

                Case ProductionIndex.Tag_Ltform_Gt_Ltdivformgt                 
                    ' <Tag> ::= '<form' <Parameters> '>' <Content> '</form>' 

                Case ProductionIndex.Tag_Ltinput_Gt                 
                    ' <Tag> ::= '<input' <Parameters> '>' 

                Case ProductionIndex.Tag_Ltselect_Gt_Ltdivselectgt                 
                    ' <Tag> ::= '<select' <Parameters> '>' <Options> '</select>' 

                Case ProductionIndex.Tag_Lttextarea_Gt_Ltdivtextareagt                 
                    ' <Tag> ::= '<textarea' <Parameters> '>' <Content> '</textarea>' 

                Case ProductionIndex.Tag_Ltusql_Gt_Ltdivusqlgt                 
                    ' <Tag> ::= '<USQL' <Parameters> '>' <Content> '</USQL>' 

                Case ProductionIndex.Tablerows_Lttr_Gt_Ltdivtrgt                 
                    ' <Table Rows> ::= '<tr' <Parameters> '>' <Table Cells> '</tr>' <Table Rows> 

                Case ProductionIndex.Tablerows                 
                    ' <Table Rows> ::=  

                Case ProductionIndex.Tablecells                 
                    ' <Table Cells> ::= <Table Cell> <Table Cells> 

                Case ProductionIndex.Tablecells2                 
                    ' <Table Cells> ::=  

                Case ProductionIndex.Tablecell_Lttd_Gt_Ltdivtdgt                 
                    ' <Table Cell> ::= '<td' <Parameters> '>' <Content> '</td>' 

                Case ProductionIndex.Tablecell_Ltth_Gt_Ltdivthgt                 
                    ' <Table Cell> ::= '<th' <Parameters> '>' <Content> '</th>' 

                Case ProductionIndex.Defitems                 
                    ' <Def Items> ::= <Def Item> <Def Items> 

                Case ProductionIndex.Defitems2                 
                    ' <Def Items> ::=  

                Case ProductionIndex.Defitem_Ltdt_Gt_Ltdivdtgt                 
                    ' <Def Item> ::= '<dt' <Parameters> '>' <Content> '</dt>' 

                Case ProductionIndex.Defitem_Ltdd_Gt_Ltdivddgt                 
                    ' <Def Item> ::= '<dd' <Parameters> '>' <Content> '</dd>' 

                Case ProductionIndex.Listitems                 
                    ' <List Items> ::= <List Item> <List Items> 

                Case ProductionIndex.Listitems2                 
                    ' <List Items> ::=  

                Case ProductionIndex.Listitem_Ltli_Gt_Ltdivligt                 
                    ' <List Item> ::= '<li' <Parameters> '>' <Content> '</li>' 

                Case ProductionIndex.Options                 
                    ' <Options> ::= <Option> <Options> 

                Case ProductionIndex.Options2                 
                    ' <Options> ::=  

                Case ProductionIndex.Option_Ltoption_Gt                 
                    ' <Option> ::= '<option' <Parameters> '>' 

                Case ProductionIndex.Mapitems                 
                    ' <Map Items> ::= <Area> <Map Items> 

                Case ProductionIndex.Mapitems2                 
                    ' <Map Items> ::=  

                Case ProductionIndex.Area_Ltarea_Gt                 
                    ' <Area> ::= '<area' <Parameters> '>' 

                Case ProductionIndex.Params_Ltparam_Gt                 
                    ' <Params> ::= '<param' <Parameters> '>' <Params> 

                Case ProductionIndex.Params                 
                    ' <Params> ::=  

                Case ProductionIndex.Word_Id                 
                    ' <Word> ::= ID 

                Case ProductionIndex.Word_Symbol                 
                    ' <Word> ::= Symbol 

                Case ProductionIndex.Word_Eq                 
                    ' <Word> ::= '=' 

                Case ProductionIndex.Word_Apost                 
                    ' <Word> ::= '' 

                Case ProductionIndex.Word_Charname                 
                    ' <Word> ::= CharName 

                Case ProductionIndex.Word_Charnumber                 
                    ' <Word> ::= CharNumber 

                Case ProductionIndex.Word_Color                 
                    ' <Word> ::= Color 

            End Select
        End With     

        Return Result
    End Function
End Module
